// src/lib/cities.ts
// 19 verified cities across Socrata + ArcGIS + CKAN.
// Denver multi-endpoint. Miami-Dade statusMap. Boston via CKAN.
// Replace your current src/lib/cities.ts with this entire file

export interface CityConfig {
  name: string;
  slug: string;
  state: string;
  stateSlug: string;
  endpoint?: string;
  endpoints?: string[];
  platform?: "socrata" | "arcgis" | "ckan";
  ckanBaseUrl?: string;
  addressField?: string;
  streetField?: string | null;
  typeField?: string;
  dateField?: string;
  statusField?: string;
  valueField?: string;
  descField?: string;
  workTypeField?: string;
  ownerField?: string;
  permitteeField?: string;
  contractorFromContacts?: boolean;
  statusMap?: Record<string, string>;
  totalPermits?: string;
  population?: string;
  permitAuthority: string;
  permitAuthorityUrl?: string;
  avgReviewDays?: number;
  tier: 1 | 2;
}

export interface StateConfig {
  name: string;
  slug: string;
  abbr: string;
  population: string;
  topCities: string[];
  permitAuthority: string;
}

// ═══════════════════════════════════════════════════════════
// TIER 1: LIVE DATA CITIES
// ═══════════════════════════════════════════════════════════

export const LIVE_CITIES: Record<string, CityConfig> = {
  "new-york": {
    name: "New York City",
    slug: "new-york",
    state: "NY",
    stateSlug: "new-york",
    endpoint: "https://data.cityofnewyork.us/resource/ipu4-2q9a.json",
    addressField: "house__",
    streetField: "street_name",
    typeField: "permit_type",
    dateField: "issuance_date",
    statusField: "permit_status",
    valueField: "permit_si_no",
    descField: "work_type",
    workTypeField: "job_type",
    ownerField: "owner_s_business_name",
    permitteeField: "permittee_s_business_name",
    totalPermits: "4.87M+",
    population: "8.3M",
    permitAuthority: "NYC Department of Buildings (DOB)",
    permitAuthorityUrl: "https://www.nyc.gov/site/buildings/index.page",
    avgReviewDays: 14,
    tier: 1,
  },
  "san-francisco": {
    name: "San Francisco",
    slug: "san-francisco",
    state: "CA",
    stateSlug: "california",
    endpoint: "https://data.sfgov.org/resource/i98e-djp9.json",
    addressField: "street_number",
    streetField: "street_name",
    typeField: "permit_type_definition",
    dateField: "issued_date",
    statusField: "status",
    valueField: "revised_cost",
    descField: "description",
    totalPermits: "1.2M+",
    population: "808k",
    permitAuthority: "SF Department of Building Inspection (DBI)",
    permitAuthorityUrl: "https://sfdbi.org/",
    avgReviewDays: 21,
    tier: 1,
  },
  "chicago": {
    name: "Chicago",
    slug: "chicago",
    state: "IL",
    stateSlug: "illinois",
    endpoint: "https://data.cityofchicago.org/resource/ydr8-5enu.json",
    addressField: "street_number",
    streetField: "street_name",
    typeField: "permit_type",
    dateField: "application_start_date",
    statusField: "permit_status",
    valueField: "reported_cost",
    descField: "work_description",
    contractorFromContacts: true,
    totalPermits: "890k+",
    population: "2.7M",
    permitAuthority: "Chicago Department of Buildings",
    permitAuthorityUrl: "https://www.chicago.gov/city/en/depts/bldgs.html",
    avgReviewDays: 18,
    tier: 1,
  },
  "austin": {
    name: "Austin",
    slug: "austin",
    state: "TX",
    stateSlug: "texas",
    endpoint: "https://data.austintexas.gov/resource/3syk-w9eu.json",
    addressField: "original_address1",
    streetField: null,
    typeField: "permit_type_desc",
    dateField: "issue_date",
    statusField: "status_current",
    valueField: "total_job_valuation",
    descField: "description",
    permitteeField: "contractor_company_name",
    ownerField: "contractor_full_name",
    totalPermits: "620k+",
    population: "975k",
    permitAuthority: "Austin Development Services Department",
    avgReviewDays: 15,
    tier: 1,
  },
  "seattle": {
    name: "Seattle",
    slug: "seattle",
    state: "WA",
    stateSlug: "washington",
    endpoint: "https://data.seattle.gov/resource/76t5-zqzr.json",
    addressField: "originaladdress1",
    streetField: null,
    typeField: "permittypemapped",
    dateField: "issueddate",
    statusField: "statuscurrent",
    valueField: "estprojectcost",
    descField: "description",
    permitteeField: "contractorcompanyname",
    totalPermits: "410k+",
    population: "750k",
    permitAuthority: "Seattle Department of Construction & Inspections",
    avgReviewDays: 20,
    tier: 1,
  },
  "los-angeles": {
    name: "Los Angeles",
    slug: "los-angeles",
    state: "CA",
    stateSlug: "california",
    endpoint: "https://data.lacity.org/resource/pi9x-tg5x.json",
    addressField: "primary_address",
    streetField: null,
    typeField: "permit_type",
    dateField: "issue_date",
    statusField: "status_desc",
    valueField: "valuation",
    descField: "work_desc",
    totalPermits: "2.1M+",
    population: "3.9M",
    permitAuthority: "LA Department of Building & Safety (LADBS)",
    avgReviewDays: 25,
    tier: 1,
  },
  "cincinnati": {
    name: "Cincinnati",
    slug: "cincinnati",
    state: "OH",
    stateSlug: "ohio",
    endpoint: "https://data.cincinnati-oh.gov/resource/dy5r-w456.json",
    addressField: "originaladdress1",
    streetField: null,
    typeField: "permittypemapped",
    dateField: "issueddate",
    statusField: "statuscurrentmapped",
    valueField: "estprojectcostdec",
    descField: "description",
    permitteeField: "companyname",
    totalPermits: "300k+",
    population: "310k",
    permitAuthority: "Cincinnati Department of Buildings & Inspections",
    permitAuthorityUrl: "https://www.cincinnati-oh.gov/buildings/",
    avgReviewDays: 20,
    tier: 1,
  },
  "kansas-city": {
    name: "Kansas City",
    slug: "kansas-city",
    state: "MO",
    stateSlug: "missouri",
    endpoint: "https://data.kcmo.org/resource/w8jz-wjgn.json",
    addressField: "main_address_line1",
    streetField: null,
    typeField: "permit_type",
    dateField: "issue_date",
    statusField: "permit_status",
    valueField: "valuation",
    descField: "work_class",
    totalPermits: "200k+",
    population: "510k",
    permitAuthority: "Kansas City Development Services",
    permitAuthorityUrl: "https://www.kcmo.gov/city-hall/departments/city-planning-development",
    avgReviewDays: 18,
    tier: 1,
  },
  "washington-dc": {
    name: "Washington",
    slug: "washington-dc",
    state: "DC",
    stateSlug: "district-of-columbia",
    platform: "arcgis",
    endpoint: "https://maps2.dcgis.dc.gov/dcgis/rest/services/FEEDS/DCRA/FeatureServer/17",
    addressField: "FULL_ADDRESS",
    streetField: null,
    typeField: "PERMIT_TYPE_NAME",
    dateField: "ISSUE_DATE",
    statusField: "APPLICATION_STATUS_NAME",
    valueField: "",
    descField: "DESC_OF_WORK",
    ownerField: "OWNER_NAME",
    totalPermits: "150k+",
    population: "690k",
    permitAuthority: "DC Department of Buildings (DOB)",
    permitAuthorityUrl: "https://dob.dc.gov/",
    avgReviewDays: 20,
    tier: 1,
  },
  "nashville": {
    name: "Nashville",
    slug: "nashville",
    state: "TN",
    stateSlug: "tennessee",
    platform: "arcgis",
    endpoint: "https://services2.arcgis.com/HdTo6HJqh92wn4D8/arcgis/rest/services/Building_Permits_Issued_2/FeatureServer/0",
    addressField: "Address",
    streetField: null,
    typeField: "Permit_Type_Description",
    dateField: "Date_Issued",
    statusField: "",
    valueField: "Const_Cost",
    descField: "Purpose",
    permitteeField: "Contact",
    totalPermits: "250k+",
    population: "690k",
    permitAuthority: "Metro Nashville Codes & Building Safety",
    permitAuthorityUrl: "https://www.nashville.gov/departments/codes-and-building-safety",
    avgReviewDays: 18,
    tier: 1,
  },
  "denver": {
    name: "Denver",
    slug: "denver",
    state: "CO",
    stateSlug: "colorado",
    platform: "arcgis",
    endpoints: [
      "https://services1.arcgis.com/zdB7qR0BtYrg0Xpl/arcgis/rest/services/ODC_DEV_RESIDENTIALCONSTPERMIT_P/FeatureServer/316",
      "https://services1.arcgis.com/zdB7qR0BtYrg0Xpl/arcgis/rest/services/ODC_DEV_COMMERCIALCONSTPERMIT_P/FeatureServer/317",
    ],
    addressField: "ADDRESS",
    streetField: null,
    typeField: "CLASS",
    dateField: "DATE_ISSUED",
    statusField: "",
    valueField: "VALUATION",
    descField: "CLASS",
    permitteeField: "CONTRACTOR_NAME",
    totalPermits: "150k+",
    population: "715k",
    permitAuthority: "Denver Community Planning & Development",
    permitAuthorityUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Community-Planning-and-Development",
    avgReviewDays: 20,
    tier: 1,
  },
  "mesa-az": {
    name: "Mesa",
    slug: "mesa-az",
    state: "AZ",
    stateSlug: "arizona",
    endpoint: "https://data.mesaaz.gov/resource/dzpk-hxfb.json",
    addressField: "property_address",
    streetField: null,
    typeField: "permit_type",
    dateField: "issued_date",
    statusField: "status",
    valueField: "total_valuation",
    descField: "description_of_work",
    totalPermits: "300k+",
    population: "510k",
    permitAuthority: "City of Mesa Development Services",
    permitAuthorityUrl: "https://www.mesaaz.gov/business/development-services",
    avgReviewDays: 15,
    tier: 1,
  },
  "tempe-az": {
    name: "Tempe",
    slug: "tempe-az",
    state: "AZ",
    stateSlug: "arizona",
    platform: "arcgis",
    endpoint: "https://services.arcgis.com/lQySeXwbBg53XWDi/ArcGIS/rest/services/building_permits/FeatureServer/0",
    addressField: "OriginalAddress1",
    streetField: null,
    typeField: "PermitTypeDesc",
    dateField: "IssuedDateDtm",
    statusField: "StatusCurrent",
    valueField: "EstProjectCost",
    descField: "Description",
    permitteeField: "ContractorCompanyName",
    totalPermits: "200k+",
    population: "185k",
    permitAuthority: "City of Tempe Community Development",
    permitAuthorityUrl: "https://www.tempe.gov/government/community-development",
    avgReviewDays: 18,
    tier: 1,
  },
  "virginia-beach": {
    name: "Virginia Beach",
    slug: "virginia-beach",
    state: "VA",
    stateSlug: "virginia",
    platform: "arcgis",
    endpoint: "https://services2.arcgis.com/CyVvlIiUfRBmMQuu/arcgis/rest/services/Building_Permits_Applications_view/FeatureServer/0",
    addressField: "StreetAddress",
    streetField: null,
    typeField: "PermitType",
    dateField: "IssueDate",
    statusField: "Status",
    valueField: "",
    descField: "WorkDesc",
    totalPermits: "100k+",
    population: "455k",
    permitAuthority: "Virginia Beach Planning Department",
    permitAuthorityUrl: "https://www.virginiabeach.gov/departments/planning",
    avgReviewDays: 18,
    tier: 1,
  },
  "phoenix-metro": {
    name: "Phoenix Metro",
    slug: "phoenix-metro",
    state: "AZ",
    stateSlug: "arizona",
    platform: "arcgis",
    endpoint: "https://services.arcgis.com/ykpntM6e3tHvzKRJ/arcgis/rest/services/Building_Permits_%28view%29/FeatureServer/0",
    addressField: "FullStreetAddress",
    streetField: null,
    typeField: "PermitType",
    dateField: "IssuedDate",
    statusField: "PermitStatus",
    valueField: "",
    descField: "PermitDescription",
    totalPermits: "100k+",
    population: "4.5M",
    permitAuthority: "Maricopa County / Phoenix Metro",
    avgReviewDays: 20,
    tier: 1,
  },
  "miami-dade": {
    name: "Miami-Dade",
    slug: "miami-dade",
    state: "FL",
    stateSlug: "florida",
    platform: "arcgis",
    endpoint: "https://services.arcgis.com/8Pc9XBTAsYuxx9Ny/arcgis/rest/services/BuildingPermit_gdb/FeatureServer/0",
    addressField: "ADDRESS",
    streetField: null,
    typeField: "DESC1",
    dateField: "ISSUDATE",
    statusField: "BPSTATUS",
    statusMap: { A: "Active", E: "Expired", F: "Finalized" },
    valueField: "",
    descField: "DESC1",
    permitteeField: "CONTRNAME",
    totalPermits: "100k+",
    population: "2.7M",
    permitAuthority: "Miami-Dade County Building Department",
    permitAuthorityUrl: "https://www.miamidade.gov/global/economy/building/home.page",
    avgReviewDays: 20,
    tier: 1,
  },
  "buffalo": {
    name: "Buffalo",
    slug: "buffalo",
    state: "NY",
    stateSlug: "new-york",
    endpoint: "https://data.buffalony.gov/resource/9p2d-f3yt.json",
    addressField: "stname",
    streetField: null,
    typeField: "aptype",
    dateField: "issued",
    statusField: "",
    valueField: "value",
    descField: "descofwork",
    permitteeField: "applicant",
    totalPermits: "200k+",
    population: "275k",
    permitAuthority: "Buffalo Department of Permit & Inspection Services",
    permitAuthorityUrl: "https://www.buffalony.gov/1376/Public-Data",
    avgReviewDays: 18,
    tier: 1,
  },
  "philadelphia": {
    name: "Philadelphia",
    slug: "philadelphia",
    state: "PA",
    stateSlug: "pennsylvania",
    platform: "arcgis",
    endpoint: "https://services.arcgis.com/fLeGjb7u4uXqeF9q/arcgis/rest/services/PERMITS/FeatureServer/0",
    addressField: "address",
    streetField: null,
    typeField: "permitdescription",
    dateField: "permitissuedate",
    statusField: "status",
    valueField: "",
    descField: "approvedscopeofwork",
    permitteeField: "contractorname",
    totalPermits: "880k+",
    population: "1.6M",
    permitAuthority: "Philadelphia Department of Licenses & Inspections (L&I)",
    permitAuthorityUrl: "https://www.phila.gov/departments/department-of-licenses-and-inspections/",
    avgReviewDays: 20,
    tier: 1,
  },
  "boston": {
    name: "Boston",
    slug: "boston",
    state: "MA",
    stateSlug: "massachusetts",
    platform: "ckan",
    ckanBaseUrl: "https://data.boston.gov",
    endpoint: "6ddcd912-32a0-43df-9908-63574f8c7e77",
    addressField: "address",
    streetField: null,
    typeField: "permittypedescr",
    dateField: "issued_date",
    statusField: "status",
    valueField: "declared_valuation",
    descField: "description",
    permitteeField: "applicant",
    totalPermits: "728k+",
    population: "650k",
    permitAuthority: "Boston Inspectional Services Department (ISD)",
    permitAuthorityUrl: "https://www.boston.gov/departments/inspectional-services",
    avgReviewDays: 20,
    tier: 1,
  },
  "pittsburgh": {
    name: "Pittsburgh",
    slug: "pittsburgh",
    state: "PA",
    stateSlug: "pennsylvania",
    platform: "ckan",
    ckanBaseUrl: "https://data.wprdc.org",
    endpoint: "f4d1177a-f597-4c32-8cbf-7885f56253f6",
    addressField: "address",
    streetField: null,
    typeField: "permit_type",
    dateField: "issue_date",
    statusField: "status",
    valueField: "total_project_value",
    descField: "work_description",
    permitteeField: "contractor_name",
    totalPermits: "62k+",
    population: "300k",
    permitAuthority: "Pittsburgh Permits, Licenses & Inspections (PLI)",
    permitAuthorityUrl: "https://pittsburghpa.gov/pli/pli-permits",
    avgReviewDays: 18,
    tier: 1,
  },
};

export const INFO_CITIES: Record<string, CityConfig> = {};
export const CITIES: Record<string, CityConfig> = { ...LIVE_CITIES, ...INFO_CITIES };
export const CITIES_LIST = Object.values(CITIES);
export const LIVE_CITIES_LIST = Object.values(LIVE_CITIES);

export const STATES: Record<string, StateConfig> = {};
export const STATES_LIST = Object.values(STATES);

export const getCityBySlug = (slug: string) => CITIES[slug];
export const getCityByStateCity = (stateSlug: string, citySlug: string) =>
  CITIES_LIST.find(c => c.stateSlug === stateSlug && c.slug === citySlug);
export const getStateBySlug = (slug: string) => STATES[slug];
export const getCitiesInState = (stateSlug: string) =>
  CITIES_LIST.filter(c => c.stateSlug === stateSlug);
export const isCityLive = (slug: string) => CITIES[slug]?.tier === 1;
